theme: jekyll-theme-minimal
title: Actors and Astrology Zodiac Trends in Movie Field
description: ça marche pas!!
show_downloads: True
navigation:
  - title: Home
    url: README
  - title: Example
    url: example
