theme: jekyll-theme-minimal

title: Actors & Astrology; Zodiac Trends in Movie Field
description: Je veux dormir, je veux aller me coucher, je veux aller dans les bras de Morphée

show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
  -title: Work in progress
   url: First_Test
