theme: jekyll-theme-minimal
title: Actors and Astrology: Zodiac Trends in Movie Field
description: Je veux aller dormir, je veux me coucher, je veux fermer les yeux, je veux rompish, je veux aller dans les bras de Morphée
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
